[versions]
org-springframework-boot = "2.7.18"

[libraries]
[plugins]
io-spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.4" }
org-springframework-boot = { id = "org.springframework.boot", version.ref = "org-springframework-boot" }
